### ISSUE TITLE
Document Taskfile interface for generic applications

### ISSUE THREAD

**Issue by pmalawsk13** [devonfw/hangar#123]
There is a need to create a document explaining what the user (DevOps) should provide for being able to use Hangar in non-supported/generic application project. 

For that purpose we are going to use task file:
https://taskfile.dev/

```
Hangar Interface:
  build:
    input:
      - branch
      - path for build artifacts
    output:
      - build result in the specified path
  test:
    input:
      - branch
      - build artifact path
      - path for test results
    output:
      - test results (text / language specific output)
  quality:
    input:
      - branch
      - path for build artifact
      - URL and credentials for quality engine (e.g. SonarQube)
    output:
      - text 
// CD 
  package-image:
    input:
      - branch
      - image name
      - image tag ???
    output:
      - docker image
  push-library:
    input:
      - library name
      - version ??
      - repository-url
    output:
      - distHangar Interface:
  build:
    input:
      - branch
      - path for build artifacts
    output:
      - build result in the specified path
  test:
    input:
      - branch
      - build artifact path
      - path for test results
    output:
      - test results (text / language specific output)
  quality:
    input:
      - branch
      - path for build artifact
      - URL and credentials for quality engine (e.g. SonarQube)
    output:
      - text 
// CD 
  package-image:
    input:
      - branch
      - image name
      - image tag ???
    output:
      - docker image
  push-library:
    input:
      - library name
      - version ??
      - repository-url
    output:
      - distributable library
  deploy:
    input:
      - branch
      - docker-image name
      - credentials fo registryributable library
  deploy:
    input:
      - branch
      - docker-image name
      - credentials fo registry
```
